package com.novalpie.nativeapp.ui

import android.content.ContentValues
import android.content.Context
import android.content.Intent
import android.net.Uri
import android.os.Build
import android.os.Environment
import android.os.Handler
import android.os.Looper
import android.provider.MediaStore
import android.util.Base64
import android.webkit.JavascriptInterface
import android.webkit.WebView
import android.widget.Toast
import androidx.webkit.ScriptHandler
import androidx.webkit.WebViewCompat
import androidx.webkit.WebViewFeature
import org.json.JSONObject
import java.io.ByteArrayOutputStream
import java.io.File
import java.io.FileOutputStream
import java.io.InputStream
import java.io.OutputStream
import java.net.InetAddress
import java.net.ServerSocket
import java.net.Socket
import java.net.URLDecoder
import java.net.URLEncoder
import java.nio.charset.StandardCharsets
import java.util.Collections
import java.util.Locale
import java.util.UUID
import java.util.WeakHashMap
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.atomic.AtomicLong

/**
 * Saves the final download Blob produced by the source website.
 *
 * The site remains responsible for EPUB generation and image fetching. This class only transports
 * the already-generated bytes from the WebView to Android Downloads, so the native app never has
 * a second opportunity to append chapter illustrations.
 */
internal class WebDownloadBridge(context: Context) {
    private val appContext = context.applicationContext
    private val mainHandler = Handler(Looper.getMainLooper())
    private val uploadToken = UUID.randomUUID().toString()
    private val serverLock = Any()
    private val downloadGate = WebDownloadIdempotencyGate()
    private val chunkSessions = ConcurrentHashMap<String, ChunkSession>()
    // Keep the app's API 23 floor: ConcurrentHashMap.newKeySet() is only available from API 24.
    private val activeSockets = Collections.synchronizedSet(mutableSetOf<Socket>())
    private val nextChunkId = AtomicLong(1L)
    private val documentStartScripts = WeakHashMap<WebView, ScriptHandler>()

    @Volatile
    private var running = false

    @Volatile
    private var uploadServer: ServerSocket? = null

    @Volatile
    private var uploadPort: Int = -1

    val javascriptInterface: BridgeInterface = BridgeInterface()

    fun start() {
        synchronized(serverLock) {
            if (running && uploadServer != null && uploadServer?.isClosed == false) return
            runCatching {
                val server = ServerSocket(0, 16, InetAddress.getByName("127.0.0.1"))
                uploadServer = server
                uploadPort = server.localPort
                running = true
                Thread({ acceptUploads(server) }, "NovalPieBlobUploadServer").apply {
                    isDaemon = true
                    start()
                }
            }.onFailure {
                running = false
                uploadServer = null
                uploadPort = -1
                showToast("下载桥启动失败")
            }
        }
    }

    fun stop() {
        synchronized(serverLock) {
            running = false
            runCatching { uploadServer?.close() }
            uploadServer = null
            uploadPort = -1
            val sockets = synchronized(activeSockets) { activeSockets.toList() }
            sockets.forEach { socket -> runCatching { socket.close() } }
        }
        val sessions = chunkSessions.values.toList()
        chunkSessions.clear()
        sessions.forEach(::abortChunkSession)
        downloadGate.clearActive()
        synchronized(documentStartScripts) {
            documentStartScripts.values.forEach(::removeDocumentStartScript)
            documentStartScripts.clear()
        }
    }

    /** Removes only the document-start hook for a released WebView. */
    fun detachWebView(webView: WebView) {
        synchronized(documentStartScripts) {
            documentStartScripts.remove(webView)?.let(::removeDocumentStartScript)
        }
    }

    private fun removeDocumentStartScript(handler: ScriptHandler) {
        if (WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT)) {
            runCatching { handler.remove() }
        }
    }

    /**
     * Installs the bridge before website scripts can create their first Blob URL.
     *
     * [injectInto] remains as a compatibility reinjection for WebViews that do not expose the
     * AndroidX document-start feature. The script itself is idempotent, so both paths are safe.
     */
    fun installDocumentStartBridge(webView: WebView): Boolean {
        if (!WebViewFeature.isFeatureSupported(WebViewFeature.DOCUMENT_START_SCRIPT)) return false
        synchronized(documentStartScripts) {
            if (documentStartScripts.containsKey(webView)) return true
            val handler = runCatching {
                WebViewCompat.addDocumentStartJavaScript(
                    webView,
                    BLOB_DOWNLOAD_SCRIPT,
                    webDownloadDocumentStartOriginRules(),
                )
            }.getOrNull() ?: return false
            documentStartScripts[webView] = handler
            return true
        }
    }

    fun injectInto(webView: WebView) {
        webView.evaluateJavascript(BLOB_DOWNLOAD_SCRIPT, null)
    }

    fun captureDownloadListenerBlob(
        webView: WebView,
        url: String?,
        filename: String?,
        mimeType: String?
    ) {
        if (!url.orEmpty().startsWith("blob:", ignoreCase = true)) return
        val script = "window.__NOVALPIE_CAPTURE_BLOB_DOWNLOAD__ && " +
            "window.__NOVALPIE_CAPTURE_BLOB_DOWNLOAD__(${JSONObject.quote(url)}," +
            "${JSONObject.quote(filename.orEmpty())},${JSONObject.quote(mimeType.orEmpty())});"
        webView.evaluateJavascript(script, null)
    }

    private fun acceptUploads(server: ServerSocket) {
        while (!server.isClosed) {
            runCatching {
                val socket = server.accept()
                activeSockets.add(socket)
                Thread({ handleUpload(socket) }, "NovalPieBlobUploadWorker").apply {
                    isDaemon = true
                    start()
                }
            }.onFailure {
                if (!server.isClosed) showToast("下载连接失败")
            }
        }
    }

    private fun handleUpload(socket: Socket) {
        try {
            socket.use { client ->
                var claimedKey: String? = null
                var claimedByThisRequest = false
                var destination: DownloadDestination? = null
                var destinationPublished = false
                runCatching {
                    client.soTimeout = 120_000
                    val input = client.getInputStream()
                    val output = client.getOutputStream()
                    val requestLine = readHttpLine(input)
                    if (requestLine.isNullOrBlank()) {
                        writeResponse(output, 400, "Bad Request", "Bad Request")
                        return
                    }

                val requestParts = requestLine.split(' ', limit = 3)
                if (requestParts.size < 2) {
                    writeResponse(output, 400, "Bad Request", "Bad Request")
                    return
                }
                val method = requestParts[0].uppercase(Locale.ROOT)
                val target = requestParts[1]
                val headers = readHeaders(input)

                if (method == "OPTIONS") {
                    writeCorsPreflight(output)
                    return
                }
                if (method != "POST" || !target.startsWith("/novalpie-blob-upload")) {
                    writeResponse(output, 404, "Not Found", "Not Found")
                    return
                }
                ensureRunning()

                val query = parseQuery(target.substringAfter('?', ""))
                if (query["token"] != uploadToken) {
                    writeResponse(output, 403, "Forbidden", "Forbidden")
                    return
                }

                val key = query["key"].orEmpty().ifBlank { UUID.randomUUID().toString() }
                claimedKey = key
                val gate = claimDownloadKey(key)
                if (!gate) {
                    drainBody(input, headers)
                    if (downloadGate.isCompleted(key)) {
                        writeJson(output, "{\"ok\":true,\"duplicate\":true}")
                    } else {
                        writeResponse(output, 409, "Conflict", "Download already in progress")
                    }
                    return
                }
                claimedByThisRequest = true

                val requestedName = query["filename"]
                val requestedMime = query["mime"] ?: headers["content-type"]
                destination = try {
                    createDestination(requestedName, requestedMime)
                } catch (error: Throwable) {
                    downloadGate.release(key)
                    writeResponse(output, 500, "Internal Server Error", error.message ?: "Cannot create download")
                    return
                }

                try {
                    ensureRunning()
                    destination!!.output.use { stream ->
                        if (headers["transfer-encoding"]?.contains("chunked", ignoreCase = true) == true) {
                            copyChunkedBody(input, stream)
                        } else {
                            copyFixedBody(input, stream, headers["content-length"]?.toLongOrNull() ?: -1L)
                        }
                        stream.flush()
                    }
                    commitDestination(destination!!)
                    destinationPublished = true
                    downloadGate.complete(key)
                    showSavedToast(destination!!.displayName)
                    runCatching {
                        writeJson(output, "{\"ok\":true,\"filename\":${JSONObject.quote(destination!!.displayName)}}")
                    }
                } catch (error: Throwable) {
                    if (!destinationPublished) {
                        downloadGate.release(key)
                        closeAndDelete(destination!!)
                        writeResponse(output, 500, "Internal Server Error", error.message ?: "Download failed")
                    } else if (!downloadGate.isCompleted(key)) {
                        // The bytes are already published. A broken response socket must not make
                        // the completed file disappear or start a second transfer on retry.
                        downloadGate.release(key)
                    }
                }
                }.onFailure { error ->
                    if (!destinationPublished) {
                        claimedKey?.let { key ->
                            if (claimedByThisRequest && !downloadGate.isCompleted(key)) downloadGate.release(key)
                        }
                        destination?.let { pending ->
                            if (claimedKey == null || !downloadGate.isCompleted(claimedKey)) {
                                closeAndDelete(pending)
                            }
                        }
                    }
                    writeResponseSafely(client, 500, "Internal Server Error", error.message ?: "Download failed")
                }
            }
        } finally {
            activeSockets.remove(socket)
        }
    }

    private fun ensureRunning() {
        if (!running) throw IllegalStateException("Download bridge is stopped")
    }

    /** Publishes only while stop() cannot concurrently invalidate this transfer. */
    private fun commitDestination(destination: DownloadDestination) {
        synchronized(serverLock) {
            ensureRunning()
            publishDestination(destination)
        }
    }

    private fun abortChunkSession(session: ChunkSession) {
        synchronized(session) {
            if (session.cancelled) return
            session.cancelled = true
            closeAndDelete(session.destination)
        }
        downloadGate.release(session.key)
    }

    private fun readHeaders(input: InputStream): MutableMap<String, String> {
        val headers = linkedMapOf<String, String>()
        while (true) {
            val line = readHttpLine(input) ?: break
            if (line.isEmpty()) break
            val separator = line.indexOf(':')
            if (separator > 0) {
                headers[line.substring(0, separator).trim().lowercase(Locale.ROOT)] =
                    line.substring(separator + 1).trim()
            }
        }
        return headers
    }

    private fun readHttpLine(input: InputStream): String? {
        val bytes = ByteArrayOutputStream()
        var previous = -1
        while (bytes.size() < MAX_HTTP_LINE_BYTES) {
            val next = input.read()
            if (next < 0) return if (bytes.size() == 0) null else bytes.toString(StandardCharsets.ISO_8859_1.name())
            if (previous == '\r'.code && next == '\n'.code) {
                val raw = bytes.toByteArray()
                return String(raw, 0, (raw.size - 1).coerceAtLeast(0), StandardCharsets.ISO_8859_1)
            }
            bytes.write(next)
            previous = next
        }
        throw IllegalArgumentException("HTTP line too long")
    }

    private fun parseQuery(raw: String): Map<String, String> = raw.split('&')
        .asSequence()
        .filter { it.isNotBlank() }
        .mapNotNull { part ->
            val separator = part.indexOf('=')
            val rawKey = if (separator >= 0) part.substring(0, separator) else part
            val rawValue = if (separator >= 0) part.substring(separator + 1) else ""
            runCatching {
                URLDecoder.decode(rawKey, StandardCharsets.UTF_8.name()) to
                    URLDecoder.decode(rawValue, StandardCharsets.UTF_8.name())
            }.getOrNull()
        }
        .toMap()

    private fun drainBody(input: InputStream, headers: Map<String, String>) {
        val sink = DrainOutputStream
        if (headers["transfer-encoding"]?.contains("chunked", ignoreCase = true) == true) {
            copyChunkedBody(input, sink)
        } else {
            copyFixedBody(input, sink, headers["content-length"]?.toLongOrNull() ?: -1L)
        }
    }

    private fun copyFixedBody(input: InputStream, output: OutputStream, length: Long) {
        val buffer = ByteArray(BUFFER_BYTES)
        var remaining = length
        while (remaining != 0L) {
            val limit = if (remaining > 0) minOf(buffer.size.toLong(), remaining).toInt() else buffer.size
            val count = input.read(buffer, 0, limit)
            if (count < 0) {
                if (length >= 0) throw IllegalStateException("Upload ended early")
                break
            }
            output.write(buffer, 0, count)
            if (remaining > 0) remaining -= count
        }
        if (length >= 0 && remaining != 0L) throw IllegalStateException("Upload ended early")
    }

    private fun copyChunkedBody(input: InputStream, output: OutputStream) {
        val buffer = ByteArray(BUFFER_BYTES)
        while (true) {
            val sizeLine = readHttpLine(input) ?: throw IllegalStateException("Missing chunk size")
            val sizeToken = sizeLine.substringBefore(';').trim()
            val size = sizeToken.toLongOrNull(16) ?: throw IllegalStateException("Invalid chunk size")
            if (size == 0L) {
                while (true) {
                    val trailer = readHttpLine(input) ?: break
                    if (trailer.isEmpty()) break
                }
                return
            }
            var remaining = size
            while (remaining > 0) {
                val count = input.read(buffer, 0, minOf(buffer.size.toLong(), remaining).toInt())
                if (count < 0) throw IllegalStateException("Chunk ended early")
                output.write(buffer, 0, count)
                remaining -= count
            }
            if (input.read() != '\r'.code || input.read() != '\n'.code) {
                throw IllegalStateException("Invalid chunk terminator")
            }
        }
    }

    private fun claimDownloadKey(key: String): Boolean = downloadGate.claim(key)

    private fun createDestination(requestedName: String?, requestedMime: String?): DownloadDestination {
        val mime = requestedMime?.trim().orEmpty().ifBlank { "application/octet-stream" }
        var displayName = ensureWebDownloadExtension(
            sanitizeWebDownloadFilename(requestedName),
            mime,
        )
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
            val values = ContentValues().apply {
                put(MediaStore.MediaColumns.DISPLAY_NAME, displayName)
                put(MediaStore.MediaColumns.MIME_TYPE, mime)
                put(MediaStore.MediaColumns.RELATIVE_PATH, Environment.DIRECTORY_DOWNLOADS)
                put(MediaStore.MediaColumns.IS_PENDING, 1)
            }
            val uri = appContext.contentResolver.insert(
                MediaStore.Downloads.getContentUri(MediaStore.VOLUME_EXTERNAL_PRIMARY),
                values,
            ) ?: throw IllegalStateException("Cannot create Downloads entry")
            val output = runCatching { appContext.contentResolver.openOutputStream(uri) }
                .getOrNull()
                ?: run {
                    runCatching { appContext.contentResolver.delete(uri, null, null) }
                    throw IllegalStateException("Cannot open Downloads stream")
                }
            return DownloadDestination(displayName, mime, output, uri, null)
        }

        val directory = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS)
        if (!directory.exists() && !directory.mkdirs()) {
            throw IllegalStateException("Cannot open Downloads directory")
        }
        displayName = uniqueFileName(directory, displayName)
        val file = File(directory, displayName)
        return DownloadDestination(displayName, mime, FileOutputStream(file), null, file)
    }

    private fun publishDestination(destination: DownloadDestination) {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && destination.uri != null) {
            appContext.contentResolver.update(
                destination.uri,
                ContentValues().apply { put(MediaStore.MediaColumns.IS_PENDING, 0) },
                null,
                null,
            )
        } else {
            destination.file?.let { file ->
                appContext.sendBroadcast(Intent(Intent.ACTION_MEDIA_SCANNER_SCAN_FILE, Uri.fromFile(file)))
            }
        }
    }

    private fun closeAndDelete(destination: DownloadDestination) {
        runCatching { destination.output.close() }
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q && destination.uri != null) {
            runCatching { appContext.contentResolver.delete(destination.uri, null, null) }
        } else {
            runCatching { destination.file?.delete() }
        }
    }

    private fun uniqueFileName(directory: File, name: String): String {
        if (!File(directory, name).exists()) return name
        val dot = name.lastIndexOf('.')
        val base = if (dot > 0) name.substring(0, dot) else name
        val extension = if (dot > 0) name.substring(dot) else ""
        for (index in 1..999) {
            val candidate = "$base ($index)$extension"
            if (!File(directory, candidate).exists()) return candidate
        }
        return "$base (${System.currentTimeMillis()})$extension"
    }

    private fun writeCorsPreflight(output: OutputStream) {
        val header = "HTTP/1.1 204 No Content\r\n" +
            "Access-Control-Allow-Origin: *\r\n" +
            "Access-Control-Allow-Methods: POST, OPTIONS\r\n" +
            "Access-Control-Allow-Headers: Content-Type\r\n" +
            "Content-Length: 0\r\nConnection: close\r\n\r\n"
        output.write(header.toByteArray(StandardCharsets.US_ASCII))
        output.flush()
    }

    private fun writeJson(output: OutputStream, body: String) =
        writeResponse(output, 200, "OK", body, "application/json")

    private fun writeResponse(output: OutputStream, code: Int, reason: String, body: String) =
        writeResponse(output, code, reason, body, "text/plain; charset=utf-8")

    private fun writeResponse(
        output: OutputStream,
        code: Int,
        reason: String,
        body: String,
        contentType: String = "text/plain; charset=utf-8",
    ) {
        val bytes = body.toByteArray(StandardCharsets.UTF_8)
        val header = "HTTP/1.1 $code $reason\r\n" +
            "Content-Type: $contentType\r\n" +
            "Access-Control-Allow-Origin: *\r\n" +
            "Content-Length: ${bytes.size}\r\nConnection: close\r\n\r\n"
        output.write(header.toByteArray(StandardCharsets.US_ASCII))
        output.write(bytes)
        output.flush()
    }

    private fun writeResponseSafely(socket: Socket, code: Int, reason: String, body: String) {
        runCatching { writeResponse(socket.getOutputStream(), code, reason, body) }
    }

    private fun showSavedToast(name: String) = showToast("已保存到下载目录: $name")

    private fun showToast(message: String) {
        mainHandler.post { Toast.makeText(appContext, message, Toast.LENGTH_SHORT).show() }
    }

    internal inner class BridgeInterface {
        @JavascriptInterface
        fun getBlobUploadUrl(filename: String?, mimeType: String?, downloadKey: String?): String {
            // start() is owned by WebFallbackScreen's lifecycle. A stale page must never be able
            // to revive the bridge after its route has been released.
            if (!running) return ""
            val port = uploadPort
            if (port <= 0) return ""
            val key = downloadKey.orEmpty().ifBlank { UUID.randomUUID().toString() }
            return "http://127.0.0.1:$port/novalpie-blob-upload" +
                "?token=${encodeQuery(uploadToken)}" +
                "&key=${encodeQuery(key)}" +
                "&filename=${encodeQuery(filename.orEmpty())}" +
                "&mime=${encodeQuery(mimeType.orEmpty())}"
        }

        @JavascriptInterface
        fun startBlobDownload(filename: String?, mimeType: String?, totalBytes: String?, downloadKey: String?): String {
            if (!running) return FAILED_SESSION
            val key = downloadKey.orEmpty().ifBlank { UUID.randomUUID().toString() }
            if (!claimDownloadKey(key)) {
                return if (downloadGate.isCompleted(key)) DUPLICATE_SESSION else IN_PROGRESS_SESSION
            }
            val destination = try {
                createDestination(filename, mimeType)
            } catch (error: Throwable) {
                downloadGate.release(key)
                showToast("下载文件创建失败")
                return FAILED_SESSION
            }
            val id = nextChunkId.getAndIncrement().toString()
            chunkSessions[id] = ChunkSession(id, key, destination, totalBytes?.toLongOrNull() ?: -1L)
            return id
        }

        @JavascriptInterface
        fun appendBlobDownloadChunk(id: String?, base64Chunk: String?): Boolean {
            val session = chunkSessions[id] ?: return false
            if (base64Chunk == null) return false
            return runCatching {
                synchronized(session) {
                    ensureRunning()
                    if (session.cancelled) throw IllegalStateException("Download session is closed")
                    val bytes = Base64.decode(base64Chunk, Base64.DEFAULT)
                    session.destination.output.write(bytes)
                    session.bytesWritten += bytes.size
                }
                true
            }.getOrElse {
                failBlobDownload(id, it.message)
                false
            }
        }

        @JavascriptInterface
        fun finishBlobDownload(id: String?): Boolean {
            val session = id?.let(chunkSessions::remove) ?: return false
            var destinationPublished = false
            return runCatching {
                synchronized(session) {
                    ensureRunning()
                    if (session.cancelled) throw IllegalStateException("Download session is closed")
                    if (session.expectedBytes >= 0L && session.bytesWritten != session.expectedBytes) {
                        throw IllegalStateException("Download ended early")
                    }
                    session.destination.output.flush()
                    session.destination.output.close()
                }
                commitDestination(session.destination)
                destinationPublished = true
                downloadGate.complete(session.key)
                showSavedToast(session.destination.displayName)
                true
            }.getOrElse {
                if (!destinationPublished) {
                    downloadGate.release(session.key)
                    synchronized(session) {
                        if (!session.cancelled) {
                            session.cancelled = true
                            closeAndDelete(session.destination)
                        }
                    }
                } else if (!downloadGate.isCompleted(session.key)) {
                    downloadGate.release(session.key)
                }
                showToast("下载保存失败")
                false
            }
        }

        @JavascriptInterface
        fun failBlobDownload(id: String?, message: String?) {
            val session = id?.let(chunkSessions::remove) ?: return
            synchronized(session) {
                if (session.cancelled) return
                session.cancelled = true
                closeAndDelete(session.destination)
            }
            downloadGate.release(session.key)
            showToast(message?.takeIf(String::isNotBlank) ?: "下载失败")
        }
    }

    private data class DownloadDestination(
        val displayName: String,
        val mimeType: String,
        val output: OutputStream,
        val uri: Uri?,
        val file: File?,
    )

    private data class ChunkSession(
        val id: String,
        val key: String,
        val destination: DownloadDestination,
        val expectedBytes: Long,
        var bytesWritten: Long = 0L,
        var cancelled: Boolean = false,
    )

    private object DrainOutputStream : OutputStream() {
        override fun write(b: Int) = Unit
        override fun write(bytes: ByteArray, offset: Int, length: Int) = Unit
    }

    companion object {
        private const val BUFFER_BYTES = 128 * 1024
        private const val MAX_HTTP_LINE_BYTES = 16 * 1024
        private const val DUPLICATE_SESSION = "__NOVALPIE_DUPLICATE__"
        private const val IN_PROGRESS_SESSION = "__NOVALPIE_IN_PROGRESS__"
        private const val FAILED_SESSION = "-1"
    }
}

/** Small synchronized state machine shared by HTTP and chunked transports. */
internal class WebDownloadIdempotencyGate(
    private val nowMillis: () -> Long = System::currentTimeMillis,
    private val retentionMillis: Long = 10 * 60 * 1000L,
) {
    private val completed = mutableMapOf<String, Long>()
    private val active = mutableSetOf<String>()

    @Synchronized
    fun claim(key: String): Boolean {
        prune()
        if (completed.containsKey(key)) return false
        return active.add(key)
    }

    @Synchronized
    fun complete(key: String) {
        active.remove(key)
        completed[key] = nowMillis()
    }

    @Synchronized
    fun release(key: String) {
        active.remove(key)
    }

    @Synchronized
    fun isCompleted(key: String): Boolean {
        prune()
        return completed.containsKey(key)
    }

    @Synchronized
    fun clearActive() {
        active.clear()
    }

    @Synchronized
    private fun prune() {
        val cutoff = nowMillis() - retentionMillis
        val iterator = completed.entries.iterator()
        while (iterator.hasNext()) {
            if (iterator.next().value < cutoff) iterator.remove()
        }
    }
}

internal fun sanitizeWebDownloadFilename(value: String?): String {
    val raw = value.orEmpty().trim()
        .removeSurrounding("\"")
        .replace(Regex("[\\u0000-\\u001f\\u007f]"), "")
        .replace(Regex("[/\\\\:*?\"<>|]"), "_")
        .trim()
    return raw.ifBlank { "novalpie_${System.currentTimeMillis()}" }
}

internal fun ensureWebDownloadExtension(filename: String, mimeType: String?): String {
    if (Regex("\\.[A-Za-z0-9]{1,8}$").containsMatchIn(filename)) return filename
    val mime = mimeType.orEmpty().lowercase(Locale.ROOT)
    return when {
        "epub" in mime -> "$filename.epub"
        "text" in mime -> "$filename.txt"
        "pdf" in mime -> "$filename.pdf"
        else -> "$filename.bin"
    }
}

internal fun webDownloadQueryEncode(value: String): String =
    URLEncoder.encode(value, StandardCharsets.UTF_8.name())

/** The download bridge is intentionally limited to the first-party HTTPS document. */
internal fun webDownloadDocumentStartOriginRules(): Set<String> = setOf("https://novalpie.cc")

private fun encodeQuery(value: String): String = webDownloadQueryEncode(value)

/**
 * The page-side half of the bridge. It intentionally never parses chapter text or image URLs.
 */
@Suppress("ConstPropertyName")
internal const val BLOB_DOWNLOAD_SCRIPT = """
(function () {
  if (window.__NOVALPIE_BLOB_DOWNLOAD_BRIDGE__) return true;
  window.__NOVALPIE_BLOB_DOWNLOAD_BRIDGE__ = true;
  var blobStore = new Map();
  var blobKeys = new WeakMap();
  var inFlight = new Set();
  var transferPromises = new Map();
  var downloadPromises = new Map();
  var completed = new Set();
  var completedKeys = new Set();
  window.__NOVALPIE_BLOB_STORE__ = blobStore;

  var nativeCreate = window.URL && URL.createObjectURL ? URL.createObjectURL.bind(URL) : null;
  var nativeRevoke = window.URL && URL.revokeObjectURL ? URL.revokeObjectURL.bind(URL) : null;
  if (nativeCreate) {
    URL.createObjectURL = function (value) {
      var url = nativeCreate(value);
      try {
        if (value && typeof value.size === 'number' && typeof value.slice === 'function') {
          blobStore.set(url, value);
          if (!blobKeys.has(value)) {
            blobKeys.set(value, 'blob-transfer-' + Date.now() + '-' + Math.random().toString(36).slice(2));
          }
        }
      } catch (_) {}
      return url;
    };
  }
  if (nativeRevoke) {
    URL.revokeObjectURL = function (url) {
      // The site commonly revokes the URL immediately after anchor.click(). Keep the Blob until
      // the native upload has completed, otherwise a legitimate EPUB can become zero bytes.
      try {
        setTimeout(function () {
          if (!inFlight.has(url)) blobStore.delete(url);
        }, 60000);
      } catch (_) {}
      return nativeRevoke(url);
    };
  }

  function extensionForMime(filename, mime) {
    if (/\.[A-Za-z0-9]{1,8}$/.test(filename)) return filename;
    mime = String(mime || '').toLowerCase();
    if (mime.indexOf('epub') >= 0) return filename + '.epub';
    if (mime.indexOf('text') >= 0) return filename + '.txt';
    if (mime.indexOf('pdf') >= 0) return filename + '.pdf';
    return filename + '.bin';
  }

  function filenameFor(anchor, blob, fallback) {
    var filename = '';
    try { filename = anchor && anchor.getAttribute('download') || ''; } catch (_) {}
    if (!filename) filename = fallback || '';
    if (!filename) {
      try { filename = String(document.title || 'novalpie').replace(/\s+/g, ' ').trim(); } catch (_) {}
    }
    if (!filename) filename = 'novalpie_' + Date.now();
    return extensionForMime(filename, blob && blob.type || '');
  }

  function readChunkAsBase64(chunk) {
    return new Promise(function (resolve, reject) {
      var reader = new FileReader();
      reader.onerror = function () { reject(reader.error || new Error('Cannot read download chunk')); };
      reader.onload = function () {
        var dataUrl = String(reader.result || '');
        var comma = dataUrl.indexOf(',');
        resolve(comma >= 0 ? dataUrl.slice(comma + 1) : dataUrl);
      };
      reader.readAsDataURL(chunk);
    });
  }

  async function saveByChunks(blob, filename, mime, key) {
    if (!AndroidDownload.startBlobDownload || !AndroidDownload.appendBlobDownloadChunk ||
        !AndroidDownload.finishBlobDownload) {
      throw new Error('Android chunk download bridge unavailable');
    }
    var id = AndroidDownload.startBlobDownload(filename, mime || blob.type || 'application/octet-stream',
        String(blob.size || 0), key);
    if (!id || id === '-1') throw new Error('Cannot open Android download file');
    if (id === '__NOVALPIE_DUPLICATE__') return;
    if (id === '__NOVALPIE_IN_PROGRESS__') {
      // A previous page instance still owns this key. Do not report success for a transfer that
      // this page did not start; the caller remains retryable after the active session finishes.
      throw new Error('Android download already in progress');
    }
    var chunkSize = 128 * 1024;
    try {
      for (var offset = 0; offset < blob.size; offset += chunkSize) {
        var base64 = await readChunkAsBase64(blob.slice(offset, Math.min(offset + chunkSize, blob.size)));
        if (AndroidDownload.appendBlobDownloadChunk(id, base64) === false) {
          throw new Error('Android download chunk write failed');
        }
      }
      if (AndroidDownload.finishBlobDownload(id) === false) {
        throw new Error('Android download finalize failed');
      }
    } catch (error) {
      try { if (AndroidDownload.failBlobDownload) AndroidDownload.failBlobDownload(id, String(error && error.message || error)); } catch (_) {}
      throw error;
    }
  }

  // A site can create two object URLs for the same generated Blob. Use the Blob object's stable
  // identity rather than the URL as the native transfer key so both paths collapse to one file.
  function downloadKeyFor(href, blob) {
    try {
      if (blob && typeof blob === 'object') {
        var key = blobKeys.get(blob);
        if (!key) {
          key = 'blob-transfer-' + Date.now() + '-' + Math.random().toString(36).slice(2);
          blobKeys.set(blob, key);
        }
        return key;
      }
    } catch (_) {}
    return href;
  }

  // Keep both transports behind one promise per Blob identity. The raw Blob POST is deliberately
  // first: it is the old WebView path that avoids materializing every 128 KiB chunk as a second
  // Base64 string, which matters for large EPUBs. The chunk bridge remains a compatibility
  // fallback for WebView versions that cannot stream a Blob body to localhost. The shared key
  // still prevents a fallback request from publishing a second file after a partial failure.
  async function transferBlob(blob, filename, mime, key) {
    var uploadUrl = AndroidDownload.getBlobUploadUrl(filename, mime, key);
    if (!uploadUrl) throw new Error('Cannot open Android download stream');
    try {
      var response = await fetch(uploadUrl, {
        method: 'POST',
        headers: {'Content-Type': mime},
        body: blob
      });
      if (response && response.ok) return;
    } catch (_) {
      // Fall through to the chunk transport. The native key makes this safe even if the server
      // completed the file but the response was lost on the way back to WebView.
    }
    try {
      await saveByChunks(blob, filename, mime, key);
    } catch (chunkError) {
      throw chunkError;
    }
  }

  // The click interceptor and WebView's DownloadListener can report the same blob URL in the
  // same turn. Register the promise before the first await so those callbacks cannot race into
  // separate Blob reads and separate identity keys.
  function saveBlob(anchor, href, fallbackFilename, fallbackMime) {
    href = String(href || '');
    if (!/^blob:/i.test(href)) return Promise.resolve(false);
    if (completed.has(href)) return Promise.resolve(true);
    var existing = downloadPromises.get(href);
    if (existing) return existing;
    var promise = saveBlobOnce(anchor, href, fallbackFilename, fallbackMime);
    downloadPromises.set(href, promise);
    var cleanup = function () {
      if (downloadPromises.get(href) === promise) downloadPromises.delete(href);
    };
    promise.then(cleanup, cleanup);
    return promise;
  }

  async function saveBlobOnce(anchor, href, fallbackFilename, fallbackMime) {
    inFlight.add(href);
    var key = null;
    var transfer = null;
    try {
      var blob = blobStore.get(href) || null;
      if (!blob) blob = await (await fetch(href)).blob();
      if (!blob) throw new Error('Blob download data missing');
      var mime = blob.type || fallbackMime || 'application/octet-stream';
      var filename = filenameFor(anchor, blob, fallbackFilename);
      key = downloadKeyFor(href, blob);
      // A completed Blob can later receive another object URL (for example after a page-side
      // retry UI rebuilds its invisible anchor). The native gate would prevent a second file,
      // but it would still have to drain an unnecessary second large upload. Completion must use
      // the Blob identity too, not only the object URL that happened to finish first.
      if (completedKeys.has(key)) {
        completed.add(href);
        blobStore.delete(href);
        return true;
      }
      transfer = transferPromises.get(key);
      if (!transfer) {
        transfer = transferBlob(blob, filename, mime, key);
        transferPromises.set(key, transfer);
      }
      await transfer;
      completedKeys.add(key);
      completed.add(href);
      blobStore.delete(href);
      return true;
    } catch (error) {
      try {
        if (window.AndroidDownload && AndroidDownload.showToast) {
          AndroidDownload.showToast('Download failed: ' + String(error && error.message || error));
        }
      } catch (_) {}
      // Keep the URL retryable. The native session has already been aborted/cleaned up by the
      // transport, so marking this URL completed here would turn a transient failure into a
      // permanent no-op on the next tap.
      return false;
    } finally {
      if (key && transfer && transferPromises.get(key) === transfer) transferPromises.delete(key);
      inFlight.delete(href);
    }
  }

  function anchorFromTarget(target) {
    while (target && target !== document) {
      if (target.tagName && String(target.tagName).toLowerCase() === 'a') return target;
      target = target.parentNode;
    }
    return null;
  }

  function captureAnchor(anchor) {
    if (!anchor) return false;
    var href = '';
    try { href = anchor.href || anchor.getAttribute('href') || ''; } catch (_) {}
    if (!/^blob:/i.test(href)) return false;
    saveBlob(anchor, href, '', '').catch(function () {});
    return true;
  }

  window.__NOVALPIE_CAPTURE_BLOB_DOWNLOAD__ = function (href, filename, mime) {
    return saveBlob(null, href, filename || '', mime || '');
  };

  document.addEventListener('click', function (event) {
    var anchor = anchorFromTarget(event.target);
    if (!anchor || !captureAnchor(anchor)) return;
    event.preventDefault();
    event.stopImmediatePropagation();
  }, true);

  try {
    var nativeAnchorClick = HTMLAnchorElement.prototype.click;
    HTMLAnchorElement.prototype.click = function () {
      if (captureAnchor(this)) return;
      return nativeAnchorClick.apply(this, arguments);
    };
  } catch (_) {}
  return true;
})()
"""
